### ISSUE TITLE
contrast tuning tests fail in presence of noise

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDIcalc-vis-matlab#40]
@aviL221 

I made a new branch `contrast_test_fix` for this work.

For me, most 'standard' tests are passing but not the 'low_noise' or 'high_noise' tests.

Here are the standard tests, mostly passing but the 4th and 6th fail (the diagonals are 0):

```
>> [b,errormsg,b_expected,doc_output,doc_expected_output] = ct.test('standard',9,1);
>> b
b =
     1     0     0     0     0     0     0     0     0
     0     1     0     0     0     0     0     0     0
     0     0     1     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     1     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     1     0     0
     0     0     0     0     0     0     0     1     0
     0     0     0     0     0     0     0     0     1
```

Here is the low noise.

```
[b,errormsg,b_expected,doc_output,doc_expected_output] = ct.test('low_noise',9,1);
>> b
b =
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     1     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     1     0
     0     0     0     0     0     0     0     0     0
```

The matrix should have 1s on the diagonal..off diagonal ones would be okay if the results are supposed to be close. I see the third test and the 8th test pass but none of the others.

```
>> [b,errormsg,b_expected,doc_output,doc_expected_output] = ct.test('high_noise',9,1);
>> b
b =
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0
```

None of the 'high_noise' tests pass for me.

I am using

NDI-matlab: main branch

Thanks
Steve

**Comment by aviL221** [comment]
@stevevanhooser I pushed some changes to the compare_contrast_tuning_docs function. Can you please rerun the following (after deleting all the old expected docs for contrast_tuning, and creating a contrast_tuning_calc object):
`[docs, doc_output, doc_expected_output] = contrast_tuning_calc.generate_mock_docs('standard',10,'generate_expected_docs',1);`
Then run these tests:
`[b_low_noise,errormsg_low_noise,b_expected_low_noise,doc_output_low_noise,doc_expected_output_low_noise] = contrast_tuning_calc.test('low_noise',10,1);`
`[b_high_noise,errormsg_high_noise,b_expected_high_noise,doc_output_high_noise,doc_expected_output_high_noise] = contrast_tuning_calc.test('high_noise',10,1);`

Thank you!

**Comment by aviL221** [comment]
While these tests (except test 10, see below) should be working now, there are some issues I feel are unresolved:
1) C50, which is the contrast at which responses hit half the max response and is one of the parameters in the naka-rushton function, can vary strongly even for similar contrast tuning curves. For example, using parameters [10,.45, 1.5] and [19,1,1.3] produce tuning curves that are reasonable to fit data produced with the same underlying curve but with added noise. I set the tolerance for C50 to the lowest possible tolerance for which every value between 0 and 1 would pass, so it is very lenient at the moment. Is there a way for me to be confident about the tolerance without being so lenient?
2) Standard deviation increases as responses increase, so it is not consistent test by test. Test 9 in particular produces much higher standard deviations than other tests. Do you think I should set tolerances on a test-by-test basis, or should I set the tolerance such that it will pass the hardest test? Or something else entirely?
3) Test 10 has no responses expected (at least for now while negative responses can't be produced), but certain fields make this hard to test: `pref` (the preferred contrast) could be any value between 0 and 1 with fairly equal likelihood, and anovas are NaN in the expected doc but not in the output doc when produced with high noise, so they are considered incompatible. Is a curve with no responses worth testing in light of these challenges? If so, should I make specific tolerances for this test, or otherwise deal with these problematic fields?

**Comment by stevevanhooser** [comment]
Yeah c50 and RMax can trade off each other, so sometimes they move around. Maybe we should have the function also return the empirical C50. I think it is okay to raise the tolerance on it.

Some of the cases are failing for me. In high noise, 6, 9, and 10 are still failing. In low noise, test 1 failed in one run and passed in another run, and test 9 failed in one out of 3 runs. So I'd increase the tolerances a little bit.

diag(b_high_noise)'
ans =
     1     1     1     1     1     0     1     1     0     0
>> diag(b_low_noise)'
ans =
     0     1     1     1     1     1     1     1     1     1

**Comment by aviL221** [comment]
I upped the tolerances and was able to pass all the tests after running low noise and high noise once each; if you could check that tests continue to pass after multiple runs, that would be great!
This is what I'm now running: 
```
[docs, doc_output, doc_expected_output] = contrast_tuning_calc.generate_mock_docs('standard',9,'generate_expected_docs',1);
[b_low_noise,errormsg_low_noise,b_expected_low_noise,doc_output_low_noise,doc_expected_output_low_noise] = contrast_tuning_calc.test('low_noise',9,1);
[b_high_noise,errormsg_high_noise,b_expected_high_noise,doc_output_high_noise,doc_expected_output_high_noise] = contrast_tuning_calc.test('high_noise',9,1);
```
